### ISSUE TITLE
it's apparently possible to assign a role to a user without the role existing

### ISSUE THREAD

**Issue by pchtsp** [baobabsoluciones/cornflow-server#72] opened 2021-07-15 15:48 UTC
In cornflow/tests/unit/test_command.py:TestCommands.test_service_user_command() it create a service user, assigns it a role. But the roles table is empty.

**Comment by ggsdc** [comment] 2021-07-19 09:50
I think this is not a bug. You can see that in the `setUp` of the TestCommands suite you have the` RegisterToles().run(False)` so when you run the test `test_service_user_command` you actually have the roles table with the predefined roles created.

Unless I am missing something I am going to close this issue.

**Comment by ggsdc** [comment] 2021-07-19 13:35
You were right, sqlalchemy does not check if the foreign key exists before inserting data to the database, so we can assign a role that is not yet created or it doen't exist.

I am going to check if this is just sqlite or if the behaviour is the same in postgresql

**Comment by ggsdc** [comment] 2021-07-19 13:40
Ok, so the problem comes from sqlite, which does not check if the foreign key exists before inserting it into the database, where postgres does so it raises an error such as: 

```
psycopg2.errors.ForeignKeyViolation: insert or update on table "user_role" violates foreign key constraint "user_role_role_id_fkey"
DETAIL:  Key (role_id)=(2) is not present in table "roles".
```

This makes me think that maybe we should duplicate our unit test so they are both run against sqlite and postgresql, that way we can be sure that we can support both databases and that the ORM and CRUD operations comply with both engines.

I expect that this change is going to need a new github actions flow where we would likely have to first fix other errors and then we can check this specific case for the roles.

@pchtsp what do you think?

**Comment by pchtsp** [comment] 2021-07-19 14:19
including unittests with postgresql will be hard since we would need to deploy a postgresql instance. Is that why you propose a new github actions flow with postgresql? In that case, we do not need to duplicate unittests, only run them in a separate flow with a postgresql database.

At the very least, we should internally check if the role exists before assigning it to the user (as we do with other things). Unless you have an alternative proposal on how to deal with postgresql exceptions.

**Comment by ggsdc** [comment] 2021-07-19 14:22
Yes, I just want to have a new github action with postgres, but with same unit tests, sorry for the missunderstanding. I'm already working on it, but I have found a couple of unittest that do not pass with postgres (on local on my machine).

I will think on how to handle this situations that could arise in other situations and think if we can do it in an simple and clean way.

**Closed** 2021-11-10 14:36 UTC
Labels: bug, cornflow-server
